project:
  type: website

execute:
  freeze: auto

website:
  title: Parallelism in Numerical Python Libraries
  navbar:
    left:
      - href: index.qmd
        text: " "
  page-footer:
    center:
      - icon: github
        href: https://github.com/thomasjpfan/parallelism-python-libraries-design

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



